language: python

matrix:
    include:
        - python: 3.5
          env:
              - TOXENV=py35

install:
    - pip install tox

script: tox

env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
